version: "3.8"

services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - ./backend/models:/app/backend/models
            - ./backend/static:/app/backend/static
        environment:
            - HOST=0.0.0.0

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "80:80"
        depends_on:
            - backend
